//
//  Restaurant.swift
//  DinnerRoll
//
//  Created by Michael Hulet on 9/26/17.
//  Copyright © 2017 Michael Hulet. All rights reserved.
//

import Foundation
import MapKit

class Restaurant: NSObject, MKAnnotation, Codable{
    let id: String
    let name: String
    // sourcery:codingName = "twitter"
    let twitterUsername: String?
    let phone: String?
    let address: String?
    let crossStreet: String?
    let city: String?
    let state: String?
    let postalCode: String?
    let country: String?
    let location: CLLocationCoordinate2D
    let categories: [Category]
    let verified: Bool
    let isOpen: Bool?
    let price: Int?
    // sourcery:excludeCoding
    lazy private(set) var primaryCategory: Category? = {
        return categories.first(where: { (category: Category) -> Bool in
            return category.isPrimary(for: self)
        })
    }()

    enum CodingKeys: String, CodingKey{
        // These are extra keys that will be needed to properly decode all fields/containers
        case contact
        case hours
        case tier
        // The rest are generated by Sourcery
// sourcery:inline:Restaurant.CodingKeys.AutoCodable
        case id 
        case name 
        case twitterUsername = "twitter"
        case phone 
        case address 
        case crossStreet 
        case city 
        case state 
        case postalCode 
        case country 
        case location 
        case categories 
        case verified 
        case isOpen 
        case price 
// sourcery:end
    }

    required init(from decoder: Decoder) throws {
        let topContainer = try decoder.container(keyedBy: CodingKeys.self)
        id = try topContainer.decode(String.self, forKey: .id)
        name = try topContainer.decode(String.self, forKey: .name)
        location = try topContainer.decode(CLLocationCoordinate2D.self, forKey: .location)
        categories = try topContainer.decode([Category].self, forKey: .categories)
        verified = try topContainer.decodeIfPresent(Bool.self, forKey: .verified) ?? false

        let locationContainer = try topContainer.nestedContainer(keyedBy: CodingKeys.self, forKey: .location)

        address = try locationContainer.decodeIfPresent(String.self, forKey: .address)
        crossStreet = try locationContainer.decodeIfPresent(String.self, forKey: .crossStreet)
        city = try locationContainer.decodeIfPresent(String.self, forKey: .city)
        state = try locationContainer.decodeIfPresent(String.self, forKey: .state)
        postalCode = try locationContainer.decodeIfPresent(String.self, forKey: .postalCode)
        country = try locationContainer.decodeIfPresent(String.self, forKey: .country)

        if topContainer.contains(.contact){
            let contactContainer = try topContainer.nestedContainer(keyedBy: CodingKeys.self, forKey: .contact)

            twitterUsername = try contactContainer.decodeIfPresent(String.self, forKey: .twitterUsername)
            phone = try contactContainer.decodeIfPresent(String.self, forKey: .phone)
        }
        else{
            twitterUsername = nil
            phone = nil
        }

        if topContainer.contains(.hours){
            let hoursContainer = try topContainer.nestedContainer(keyedBy: CodingKeys.self, forKey: .hours)
            isOpen = try hoursContainer.decodeIfPresent(Bool.self, forKey: .isOpen)
        }
        else{
            isOpen = nil
        }

        if topContainer.contains(.price){
            let priceContainer = try topContainer.nestedContainer(keyedBy: CodingKeys.self, forKey: .price)
            price = try priceContainer.decodeIfPresent(Int.self, forKey: .tier)
        }
        else{
            price = nil
        }

        super.init()
    }

    func encode(to encoder: Encoder) -> Void{
        
    }

//    init?(json: JSON){
//        let location = json["location"]
//        guard let id = json["id"].string, let name = json["name"].string, let latitude = location["lat"].double, let longitude = location["lng"].double, let categories = json["categories"].array, let verified = json["verified"].bool else{
//            return nil
//        }
//        self.id = id
//        self.name = name
//        self.verified = verified
//        self.location = CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
//        var main: Category? = nil
//        for category in categories{
//            guard let valid = Category(json: category) else{
//                continue
//            }
//            if let primary = category["primary"].bool, primary{
//                main = valid
//            }
//            self.categories.append(valid)
//        }
//        self.primaryCategory = main
//        super.init()
//        addData(from: json)
//    }

//    func addData(from json: JSON) -> Void{
//        let location = json["location"]
//        let contactInfo = json["contact"]
//        self.twitterUsername = contactInfo["twitter"].string
//        self.phone = contactInfo["phone"].string
//        self.address = location["address"].string
//        self.crossStreet = location["crossStreet"].string
//        self.city = location["city"].string
//        self.state = location["state"].string
//        self.postalCode = location["postalCode"].string
//        self.country = location["country"].string
//        self.isOpen = json["hours"]["isOpen"].bool
//        self.price = json["price"]["tier"].int
//    }

    var coordinate: CLLocationCoordinate2D{
        get{
            return location
        }
    }
    var title: String?{
        get{
            return name
        }
    }
    var subtitle: String?{
        get{
            return address
        }
    }
 }

extension CLLocationCoordinate2D: Codable{
    enum CodingKeys: String, CodingKey{
        case latitude = "lat"
        case longitude = "lng"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.init(latitude: try container.decode(Double.self, forKey: .latitude), longitude: try container.decode(Double.self, forKey: .longitude))
    }

    public func encode(to encoder: Encoder) throws -> Void{
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(latitude, forKey: .latitude)
        try container.encode(longitude, forKey: .longitude)
    }
}
